version: '3.8'

services:
  back-end:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    container_name: softy-pinko-back-end
    ports:
      - "5252:5252"
    depends_on:
      - front-end

  front-end:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    container_name: softy-pinko-front-end
    ports:
      - "5253:5252"
    volumes:
      - ./front-end/softy-pinko-front-end:/var/www/html/softy-pinko-front-end
