services:
  front-end:
    build:
      context: ./front-end
    ports:
      - "80:80"
    depends_on:
      - proxy

  proxy:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - back-end-1
      - back-end-2

  back-end-1:
    build:
      context: ./back-end
    ports:
      - "5252"

  back-end-2:
    build:
      context: ./back-end
    ports:
      - "5253"
